### PR TITLE
Return empty string is country is nil

### LINKED ISSUE #38: Fatal Exception: NSInvalidArgumentException
Hello,
I've the package installed on one of my application, few weeks ago i've started see crashes on my app, and since i've Fabric installed i found that the issue in the below line !! any help how to fix it ?! or why even this happens ?!
[RNVersionCheck constantsToExport] (RNVersionCheck.m:42)

### PR DESCRIPTION
**Pull request by adrianchinghc**
Fix #38

### CODE REVIEW

File: packages/react-native-version-check/src/getStoreUrl.js [hunk 1]
```diff
@@ -29,9 +29,11 @@ export const getAppStoreUrl = async (
       option.country = await getVersionInfo().getCountry();
     }
 
-    return `https://itunes.apple.com/${option.country}/app/${
-      option.appName
-    }/id${option.appID}`;
+    const countryCode = !option.country ? `${option.country}/` : '';
```
Comment (kimxogus) [inline packages/react-native-version-check/src/getStoreUrl.js]: This will make only invalid codes be inserted

image
image

File: packages/react-native-version-check/src/providers/appStore.js [hunk 2]
```diff
@@ -23,9 +23,10 @@ class AppStoreProvider implements IProvider {
       if (!option.packageName) {
         option.packageName = getVersionInfo().getPackageName();
       }
+      const countryCode = !option.country ? `${option.country}/` : '';
```
Comment (kimxogus) [inline packages/react-native-version-check/src/providers/appStore.js]: This will make only invalid codes be inserted

image
image

**Comment by adrianchinghc** [comment]
@kimxogus Sorry about that! Got mixed up when I was testing. 😂
